-- MySQL Workbench Synchronization
-- Generated: 2016-12-20 00:05
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: arie syarwani

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `universitas_bersama`.`MAHASISWA` 
CHANGE COLUMN `id MAHASISWA` `id MAHASISWA` INT(11) NULL DEFAULT NULL ;

ALTER TABLE `universitas_bersama`.`DOSEN` 
CHANGE COLUMN `nama_dosen` `nama_dosen` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `email_dosen` `email_dosen` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `UserName` `UserName` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `pasword` `pasword` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `link_fb` `link_fb` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `wibsite` `wibsite` VARCHAR(45) NULL DEFAULT NULL ;

ALTER TABLE `universitas_bersama`.`NILAI` 
CHANGE COLUMN `tugas` `tugas` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `uts` `uts` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `uas` `uas` VARCHAR(45) NULL DEFAULT NULL ;

ALTER TABLE `universitas_bersama`.`MATA_KULIAH` 
CHANGE COLUMN `MATA_KULIAH` `MATA_KULIAH` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `kode` `kode` VARCHAR(45) NULL DEFAULT NULL ;

ALTER TABLE `universitas_bersama`.`INFORMASI` 
CHANGE COLUMN `judul` `judul` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `info` `info` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `tanggal` `tanggal` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `hari` `hari` VARCHAR(45) NULL DEFAULT NULL ,
ADD INDEX `fk_INFORMASI_DOSEN1_idx` (`DOSEN_id_dosen` ASC),
ADD INDEX `fk_INFORMASI_MATA_KULIAH1_idx` (`MATA_KULIAH_id_matakuliah` ASC, `MATA_KULIAH_DOSEN_id_dosen` ASC),
DROP INDEX `fk_INFORMASI_MATA_KULIAH1_idx` ,
DROP INDEX `fk_INFORMASI_DOSEN1_idx` ;

ALTER SCHEMA `new_schema1`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `new_schema1`.`gfbnk` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `ID Mahasiswa` `ID Mahasiswa` INT(11) NULL DEFAULT NULL ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
