-- MySQL Workbench Synchronization
-- Generated: 2016-12-21 21:38
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: arie syarwani

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER SCHEMA `universitas_bersama`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `universitas_bersama`.`MAHASISWA` (
  `id MAHASISWA` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `pasword` VARCHAR(45) NULL DEFAULT NULL,
  `nama_mhs` VARCHAR(45) NULL DEFAULT NULL,
  `nim_mhs` VARCHAR(45) NULL DEFAULT NULL,
  `tgl_lahir_mhs` VARCHAR(45) NULL DEFAULT NULL,
  `email_mhs` VARCHAR(45) NULL DEFAULT NULL,
  `alamat_mhs` VARCHAR(45) NULL DEFAULT NULL,
  `no_telp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id MAHASISWA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp850;

CREATE TABLE IF NOT EXISTS `universitas_bersama`.`PESERTA MK` (
  `id_peserta` INT(11) NOT NULL,
  `MAHASISWA_id MAHASISWA` INT(11) NOT NULL,
  `MATA_KULIAH_id_matakuliah` INT(11) NOT NULL,
  `MATA_KULIAH_DOSEN_id_dosen` INT(11) NOT NULL,
  `DOSEN_id_dosen` INT(11) NOT NULL,
  PRIMARY KEY (`id_peserta`, `MAHASISWA_id MAHASISWA`, `MATA_KULIAH_id_matakuliah`, `MATA_KULIAH_DOSEN_id_dosen`, `DOSEN_id_dosen`),
  INDEX `fk_PESERTA MK_MAHASISWA1_idx` (`MAHASISWA_id MAHASISWA` ASC),
  INDEX `fk_PESERTA MK_MATA_KULIAH1_idx` (`MATA_KULIAH_id_matakuliah` ASC, `MATA_KULIAH_DOSEN_id_dosen` ASC),
  INDEX `fk_PESERTA MK_DOSEN1_idx` (`DOSEN_id_dosen` ASC),
  CONSTRAINT `fk_PESERTA MK_MAHASISWA1`
    FOREIGN KEY (`MAHASISWA_id MAHASISWA`)
    REFERENCES `universitas_bersama`.`MAHASISWA` (`id MAHASISWA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESERTA MK_MATA_KULIAH1`
    FOREIGN KEY (`MATA_KULIAH_id_matakuliah` , `MATA_KULIAH_DOSEN_id_dosen`)
    REFERENCES `universitas_bersama`.`MATA_KULIAH` (`id_matakuliah` , `DOSEN_id_dosen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESERTA MK_DOSEN1`
    FOREIGN KEY (`DOSEN_id_dosen`)
    REFERENCES `universitas_bersama`.`DOSEN` (`id_dosen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `universitas_bersama`.`DOSEN` (
  `id_dosen` INT(11) NOT NULL,
  `nama_dosen` VARCHAR(45) NULL DEFAULT NULL,
  `email_dosen` VARCHAR(45) NULL DEFAULT NULL,
  `UserName` VARCHAR(45) NULL DEFAULT NULL,
  `pasword` VARCHAR(45) NULL DEFAULT NULL,
  `link_fb` VARCHAR(45) NULL DEFAULT NULL,
  `wibsite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dosen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `universitas_bersama`.`NILAI` (
  `id_nilai` INT(11) NOT NULL,
  `PESERTA MK_id_peserta` INT(11) NOT NULL,
  `tugas` VARCHAR(45) NULL DEFAULT NULL,
  `uts` VARCHAR(45) NULL DEFAULT NULL,
  `uas` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nilai`, `PESERTA MK_id_peserta`),
  INDEX `fk_NILAI_PESERTA MK1_idx` (`PESERTA MK_id_peserta` ASC),
  CONSTRAINT `fk_NILAI_PESERTA MK1`
    FOREIGN KEY (`PESERTA MK_id_peserta`)
    REFERENCES `universitas_bersama`.`PESERTA MK` (`id_peserta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `universitas_bersama`.`MATA_KULIAH` (
  `id_matakuliah` INT(11) NOT NULL,
  `DOSEN_id_dosen` INT(11) NOT NULL,
  `MATA_KULIAH` VARCHAR(45) NULL DEFAULT NULL,
  `sks` VARCHAR(45) NULL DEFAULT NULL,
  `kode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_matakuliah`, `DOSEN_id_dosen`),
  INDEX `fk_MATA_KULIAH_DOSEN1_idx` (`DOSEN_id_dosen` ASC),
  CONSTRAINT `fk_MATA_KULIAH_DOSEN1`
    FOREIGN KEY (`DOSEN_id_dosen`)
    REFERENCES `universitas_bersama`.`DOSEN` (`id_dosen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `universitas_bersama`.`INFORMASI` (
  `id_informasi` INT(11) NOT NULL,
  `DOSEN_id_dosen` INT(11) NOT NULL,
  `MATA_KULIAH_id_matakuliah` INT(11) NOT NULL,
  `judul` VARCHAR(45) NULL DEFAULT NULL,
  `info` VARCHAR(45) NULL DEFAULT NULL,
  `tanggal` VARCHAR(45) NULL DEFAULT NULL,
  `hari` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_informasi`, `DOSEN_id_dosen`, `MATA_KULIAH_id_matakuliah`),
  INDEX `fk_INFORMASI_MATA_KULIAH1_idx` (`MATA_KULIAH_id_matakuliah` ASC),
  INDEX `fk_INFORMASI_DOSEN1_idx` (`DOSEN_id_dosen` ASC),
  CONSTRAINT `fk_INFORMASI_MATA_KULIAH1`
    FOREIGN KEY (`MATA_KULIAH_id_matakuliah`)
    REFERENCES `universitas_bersama`.`MATA_KULIAH` (`id_matakuliah`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INFORMASI_DOSEN1`
    FOREIGN KEY (`DOSEN_id_dosen`)
    REFERENCES `universitas_bersama`.`DOSEN` (`id_dosen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
